name: Autotag

on:
  push:
    branches: 
    - master
     
jobs:
  tag_commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Bump version
      uses: ./.github/actions/autotag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
